[package]
name = "harmonia-daemon"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
harmonia-utils-io = { version = "0.0.0-alpha.0" }
harmonia-utils-hash = { version = "0.0.0-alpha.0" }
harmonia-store-core = { version = "0.0.0-alpha.0" }
harmonia-store-db = { version = "3.0.0" }
harmonia-nar = { version = "3.0.0" }
harmonia-protocol = { version = "3.0.0" }
bytes = { workspace = true }
libc = "0.2"
ring = { workspace = true }
tempfile = { workspace = true }
nix = { version = "0.31", features = ["user", "fs"] }
pin-project-lite = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
harmonia-nar = { version = "3.0.0", features = ["test"] }
harmonia-utils-test = { version = "0.0.0-alpha.0" }
tokio-test = "0.4"

[lints]
workspace = true
