[package]
name = "harmonia-daemon"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
harmonia-utils-io = { path = "../harmonia-utils-io" }
harmonia-utils-hash = { path = "../harmonia-utils-hash" }
harmonia-store-core = { path = "../harmonia-store-core" }
harmonia-store-db = { path = "../harmonia-store-db" }
harmonia-protocol = { path = "../harmonia-protocol" }
harmonia-nar = { path = "../harmonia-nar" }
tokio = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
